export * as querieAuth from "./authQuerie.js"
export * as queriePluviometer from "./pluviometerQuerie.js"
export * as querieDht from "./dhtQuerie.js"
export * as querieBmp from "./bmpQuerie.js"
export * as querieAnemometer from "./anemometerQuerie.js"
export * as querieStation from "./stationQuerie.js"