export * as querieClient from "./clientQuerie.js"
export * as querieCake from "./cakeQuerie.js"
export * as querieOrder from "./orderQuerie.js"
export * as querieAuth from "./authQuerie.js"
//export * as queriePluviometer from "./pluviometerQuerie.js"
export * as querieDht from "./dhtQuerie.js"