export * as clientMiddleware from "./clientMiddleware.js"
export * as cakeMiddleware from "./cakeMiddleware.js"
export * as orderMiddleware from "./orderMiddleware.js"
export * as authMiddleware from "./authMiddleware.js"
//export * as pluviometerMiddleware from "./pluviometerMiddleware.js"
export * as dhtMiddleware from "./dhtMiddleware.js"